[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["."]  # ["."] by default
include = ["*"]  # ["*"] by default
exclude = ["inputs*", "outputs*", "docs*"]
namespaces = true  # true by default

[project]
name = "stream-dse"
version = "0.0.8"
description = "Stream - Multi-core accelerator design space exploration with layer-fused scheduling"
readme = "README.md"
authors = [{ name = "Arne Symons", email = "arne.symons@kuleuven.be" }, { name = "Linyan Mei", email = "linyan.mei@kuleuven.be" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
]
keywords = ["stream", "multi-core", "accelerator", "layer-fused", "scheduling", "zigzag", "dse", "design-space-exploration", "machine-learning", "deep-learning", "mapping"]
dependencies = [
    'zigzag-dse',
    'rtree',
    'deap',
    'brokenaxes',
]
requires-python = ">=3.9"


[project.optional-dependencies]
dev = ["bumpver", "pip-tools", "build", "twine"]

[project.urls]
Homepage = "https://github.com/ZigZag-Project/stream"

[project.scripts]
realpython = "stream.__main__:main"

[tool.bumpver]
current_version = "0.0.8"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"', 
    'version = "{version}"'
]
"stream/__init__.py" = ["{version}"]



