workload = {
    0: {
        "operator_type": "layer_on_core0",
        "equation": "O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][iy][ix]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {
            "B": 1,
            "K": 64,
            "C": 3,
            "OY": 112,
            "OX": 112,
            "FY": 7,
            "FX": 7,
        },
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": []},
        "constant_operands": ["I", "W"],
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "padding": {"IY": (3, 2), "IX": (3, 2)},
    },
    1: {
        "operator_type": "layer_on_core1",
        "equation": "O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][iy][ix]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {
            "B": 1,
            "K": 64,
            "C": 64,
            "OY": 112,
            "OX": 112,
            "FY": 7,
            "FX": 7,
        },
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [0]},
        "constant_operands": ["W"],
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "padding": {"IY": (3, 2), "IX": (3, 2)},
    },
    2: {
        "operator_type": "layer_on_core2",
        "equation": "O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][iy][ix]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {
            "B": 1,
            "K": 64,
            "C": 64,
            "OY": 112,
            "OX": 112,
            "FY": 7,
            "FX": 7,
        },
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [1]},
        "constant_operands": ["W"],
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "padding": {"IY": (3, 2), "IX": (3, 2)},
    },
    3: {
        "operator_type": "layer_on_core3",
        "equation": "O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][iy][ix]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {
            "B": 1,
            "K": 64,
            "C": 64,
            "OY": 112,
            "OX": 112,
            "FY": 7,
            "FX": 7,
        },
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [2]},
        "constant_operands": ["W"],
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "padding": {"IY": (3, 2), "IX": (3, 2)},
    },
}
