site_name: Stream
site_url: https://kuleuven-micas.github.io/stream/
repo_url: https://github.com/KULeuven-MICAS/stream
repo_name: KULeuven-MICAS/stream
docs_dir: source
site_dir: site
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: lime
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.copy
    - search.suggest
    - search.highlight
    - header.autohide
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  logo: images/stream-logo.svg
  favicon: images/stream-logo.svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KULeuven-MICAS/stream
      name: GitHub
  version:
    provider: mike  # optional if you plan to version docs later

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.tasklist
  - pymdownx.mark

plugins:
  - search
  - mkdocstrings:
      default_handler: python
  - git-revision-date-localized
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - User Guide:
      - user-guide.md
      - Workload: workload.md
      - Hardware: hardware.md
      - Mapping: mapping.md
      - Stages: stages.md
      - Outputs: outputs.md
  - Future Plans: future.md
  - Contributing: contribute.md
  - Publications: publications.md