name: Python test

# Controls when the workflow will run
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Ensures submodules like mlir-aie are cloned too

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run without errors
      #   run: |
      #     python test_co.py
