name: Python main

# Controls when the workflow will run
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Ensures submodules like mlir-aie are cloned too

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          bash -exo pipefail setup.sh

      # - name: Run codegeneration for conv2d main without errors
      #   run: |
      #     python main_aie_codegen_conv2d.py --height 2
 
      - name: Run codegeneration for gemm main without errors
        run: |
          # source mlir-aie/utils/env_setup.sh
          python main_aie_codegen_gemm.py --M 64 --N 64 --K 64

      # - name: Run codegeneration for gemm on a column main without errors
      #   run: |
      #     python main_aie_codegen_gemm_col.py --M 64 --N 64 --K 64
