name: Local XRT Deployment for Gemm

on: [push]

jobs:
  test-xrt:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Check XRT SMI
        run: |
          echo "Checking xrt-smi examine"
          xrt-smi examine

      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python (optional if already on runner)
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Graphviz (optional, if not already present on runner)
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Set up environment and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          bash setup_mlir_aie_requirements.sh

      - name: Run Snakemake workflow
        run: |
          source setup_mlir_aie_pythonpath.sh
          snakemake -j 1 --forceall